CLASS zcl_6171_handler DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC FOR EVENTS OF ZMY6171_R_TRAVEL.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_6171_HANDLER IMPLEMENTATION.
ENDCLASS.
